<a href="https://colab.research.google.com/github/praveenkumarreddyaturu104/TENSORFLOW/blob/main/Colab00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing tensorflow lib
import tensorflow as tf
print(tf.__version__)

2.20.0


In [ ]:
#scalar
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim#ndim used to identify dimensions in given datatype

0

In [ ]:
#create a constant vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#check the vector dimension of vector
vector.ndim

1

In [ ]:
#creating matrix using constant
matrix=tf.constant(value=[[10,7],[7,10]],dtype=tf.float32,name="apkr")
matrix


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 7., 10.]], dtype=float32)>

In [ ]:
matrix.ndim

2

In [ ]:
#create another matrix with float
anothere_matrix=tf.constant([[10.,7.],[3.,2.],[8.,9.]],tf.float16)
anothere_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
#whats about  the dimesion of the matrix
anothere_matrix.ndim

2

In [ ]:
#lets create a tensor
tensor=tf.constant([[[1,2,3],[2,3,4],[4,5,6]]])
tensor

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
from numpy import number
#what we created so far:

#*scalar:a single number
#*vector:a 1-dimensional array of numbers
#*matrix:a 2-dimensional array of numbers
#tensor: a n dimesional array of numbers

In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
#create the same tensor with tf.Variable
changable_tensor=tf.Variable([10,7],tf.float64)
unchangable_tensor=tf.constant([10,7],tf.float64)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
#.assign()
changable_tensor[0].assign(5,tf.float64)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 7], dtype=int32)>

In [ ]:
# this is unchangable tensor cause it is constant
# no need to worry for not executing
#unchangable_tensor[0].assign(7)

In [ ]:
from re import L
#creating random tensors
random_1=tf.random.Generator.from_seed(4)
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(2)
random_2=random_2.normal(shape=(3,2))
#are they equal?
random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 1.0019135 ,  0.67351365],
        [ 0.06987712, -1.4077919 ],
        [ 1.0278524 ,  0.27974114]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.1012345 , -0.2744976 ],
        [ 1.4204658 ,  1.2609464 ],
        [-0.43640924, -1.9633987 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [ ]:
random_76=tf.random.Generator.from_seed(44)
random_76=random_76.normal(shape=(3,2))
random_76

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7535806 , -0.5716629 ],
       [ 0.1480774 , -0.23362991],
       [-0.3522796 ,  0.40621266]], dtype=float32)>

In [ ]:
### shuffle the order of the elements
not_shuffled=tf.constant([[10,7],[3,4],[2,5]])
not_shuffled.ndim
#shuffle our non_shuffled tensdor
tf.random.shuffle(not_shuffled[:,:])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.ones([4,4])

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(4,2))

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
import numpy as np
numpy_a=np.arange(9,13,dtype=np.int32)
numpy_a


array([ 9, 10, 11, 12], dtype=int32)

In [ ]:
a=tf.constant(numpy_a)
a

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 9, 10, 11, 12], dtype=int32)>

In [ ]:
t=tf.zeros(shape=(2,3,4,5))
t

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
tf.size(t),t.shape,t.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=120>, TensorShape([2, 3, 4, 5]), 4)

In [ ]:
print("data type of every element",t.dtype)
print("no of dimensions (rank):",t.ndim)
print("shape of tensor",t.shape)
print("total no pf elements",tf.size(t))
print("total no of elements in 0 axis:",t.shape[2])
print("total no of elements tensor:",tf.size(t).numpy())

data type of every element <dtype: 'float32'>
no of dimensions (rank): 4
shape of tensor (2, 3, 4, 5)
total no pf elements tf.Tensor(120, shape=(), dtype=int32)
total no of elements in 0 axis: 4
total no of elements tensor: 120


In [ ]:
#indexing tensor
t[:2,:2:,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#each dimesion from each index
t[:1,:,:1,:]

<tf.Tensor: shape=(1, 3, 1, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:



rank_2_tensor=tf.constant([[1,4],[2,4]])
#get last two item of each of our rank_2_tensor
rank_2_tensor[:,:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 4]], dtype=int32)>

In [ ]:
#add in an extra dimension to rank_2_tensor
rank_3_t=rank_2_tensor[..., tf.newaxis]
rank_3_t

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [4]],

       [[2],
        [4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [4]],

       [[2],
        [4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=0)
rank_2_tensor.ndim

2

In [ ]:
#manipulating tensor
#*basic operation
#*+-/%*


In [ ]:
tensor+14
print(tensor)

tf.Tensor(
[[[1 2 3]
  [2 3 4]
  [4 5 6]]], shape=(1, 3, 3), dtype=int32)


In [ ]:
tensor=tensor+27
print(tensor)
tensor=tensor
print(tensor)


tf.Tensor(
[[[28 29 30]
  [29 30 31]
  [31 32 33]]], shape=(1, 3, 3), dtype=int32)
tf.Tensor(
[[[28 29 30]
  [29 30 31]
  [31 32 33]]], shape=(1, 3, 3), dtype=int32)


In [ ]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[280, 290, 300],
        [290, 300, 310],
        [310, 320, 330]]], dtype=int32)>

In [ ]:
tf.add(tensor,1)

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[29, 30, 31],
        [30, 31, 32],
        [32, 33, 34]]], dtype=int32)>

In [ ]:
#matrix multiplication
#rules are regular as the same as we learn in mathematics
#very common in machine learning
#operators tensor @ tensor  ||  tf.matmul(tensor,tensor)
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[2555, 2642, 2729],
        [2643, 2733, 2823],
        [2819, 2915, 3011]]], dtype=int32)>

In [ ]:
ten1=tf.Variable([[1,2,5],[7,2,1],[3,3,3]])
ten2=tf.Variable([[3,5],[6,7],[1,8]])

In [ ]:
print(tf.matmul(ten1,ten2))

tf.Tensor(
[[20 59]
 [34 57]
 [30 60]], shape=(3, 2), dtype=int32)


In [ ]:
tensor*tensor

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[ 784,  841,  900],
        [ 841,  900,  961],
        [ 961, 1024, 1089]]], dtype=int32)>

In [ ]:
tensor@tensor

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[2555, 2642, 2729],
        [2643, 2733, 2823],
        [2819, 2915, 3011]]], dtype=int32)>

In [ ]:
ten1@ten2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
tf.expand_dims(ten2,axis=1)

<tf.Tensor: shape=(3, 1, 2), dtype=int32, numpy=
array([[[3, 5]],

       [[6, 7]],

       [[1, 8]]], dtype=int32)>

In [ ]:
ten3=tf.Variable([[3,2],[4,2],[2,4]])

In [ ]:
tensor@ten2
tensor
tensor+tensor

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[56, 58, 60],
        [58, 60, 62],
        [62, 64, 66]]], dtype=int32)>

In [ ]:
#matrix multiplication if the dimensions are equal as copy(i.e:i!=j)
#use tf.tensodot(tf.transpose(tensor),tensor,axes=1)
#tf.matmul(tensor,tf.reshape(tensor,shape=(j,i)))
#tf.matnu(tensor,tf.transpose(tensor))
#tensor @ transpose(tensor)
#!! if tensor[i,j] where i!=j
tf.tensordot(tf.transpose(ten3),ten2,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[35, 59],
       [22, 56]], dtype=int32)>

In [ ]:
ten2 @ tf.transpose(ten3)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[19, 22, 26],
       [32, 38, 40],
       [19, 20, 34]], dtype=int32)>

In [ ]:
tf.matmul(ten2,tf.transpose(ten3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[19, 22, 26],
       [32, 38, 40],
       [19, 20, 34]], dtype=int32)>

In [ ]:
tf.matmul(ten2,tf.reshape(ten3,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[19, 16, 32],
       [32, 26, 52],
       [19, 18, 36]], dtype=int32)>

In [ ]:
b=tf.constant([1.2,3.4])
b.dtype
tf.__version__
c=tf.constant([1,2,4,5])
c.dtype,b.dtype

(tf.int32, tf.float32)

In [ ]:
#changing the datatype from float32 to float16
b=tf.cast(b,dtype=tf.float16)
b.dtype

tf.float16

In [ ]:
#changing the datatype from int32 to int16
c=tf.cast(c,dtype=tf.int16)
c.dtype

tf.int16

In [ ]:
#aggregating tensors
#reduce_min
#reduce_max
#reduce_sum
#rduce_std
d=tf.constant([-7,-10])
d

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
e=tf.random.uniform(shape=[50], minval=0, maxval=100, dtype=tf.int32)
e
p=tf.random.uniform(shape=[40],minval=10,maxval=99,dtype=tf.float64)
p

<tf.Tensor: shape=(40,), dtype=float64, numpy=
array([54.778617  , 49.8680709 , 85.58166483, 61.08477695, 80.67050717,
       18.26206378, 95.17358714, 74.00658855, 73.84859816, 57.59872582,
       19.28354148, 63.71979052, 41.08486392, 88.9951773 , 68.88089882,
       19.80591381, 63.42617502, 16.92624815, 34.20958876, 37.69703534,
       28.63524076, 37.39825478, 77.92610565, 31.60740126, 80.98252292,
       65.54365883, 81.91380526, 49.93521535, 32.43985826, 91.29011815,
       43.92877673, 66.90790664, 89.52172066, 47.707042  , 10.26348293,
       35.66458357, 92.92827797, 13.83547084, 58.88757355, 56.5775725 ])>

In [ ]:
#reduce min
tf.reduce_min(p)

<tf.Tensor: shape=(), dtype=float64, numpy=10.26348293016314>

In [ ]:
#reduce max
tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=int32, numpy=99>

In [ ]:
#find sum
tf.reduce_sum(e)

<tf.Tensor: shape=(), dtype=int32, numpy=2514>

In [ ]:
import tensorflow_probability as tfp

In [ ]:
#find variance of our tensor
tfp.stats.variance(e)

<tf.Tensor: shape=(), dtype=int32, numpy=998>

In [ ]:
tf.math.reduce_std(p)

<tf.Tensor: shape=(), dtype=float64, numpy=24.598851731578755>

In [ ]:
tf.random.set_seed(42)
tf.math.reduce_variance(tf.cast(e,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=997.9215698242188>

In [ ]:
#  positonal maximum,minimum
f=tf.random.uniform(shape=[50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tfp.stats.variance(p)

<tf.Tensor: shape=(), dtype=float64, numpy=605.103506512195>

In [ ]:
#position of maximum
tf.argmax(p)
tf.argmin(p)

<tf.Tensor: shape=(), dtype=int64, numpy=34>

In [ ]:
#maximum value
f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [ ]:
#maximum value manual
tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [ ]:
f[32]

<tf.Tensor: shape=(), dtype=float32, numpy=0.8117929697036743>

In [ ]:
f[tf.argmin(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>

In [ ]:
#squeesing a tensor
tf.random.set_seed(42)
g=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
g

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
g.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
g_squeezed=tf.squeeze(g)
g_squeezed,g_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

In [ ]:
#one-hot encodeing tensors
some_list=[3,1,2,0]
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.]], dtype=float32)>

In [ ]:
tf.one_hot(some_list,depth=4,on_value="hi",off_value="bye")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'bye', b'bye', b'bye', b'hi'],
       [b'bye', b'hi', b'bye', b'bye'],
       [b'bye', b'bye', b'hi', b'bye'],
       [b'hi', b'bye', b'bye', b'bye']], dtype=object)>

In [ ]:
h=tf.range(1,10)
h

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(h)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(h,dtype=tf.float32))
tf.sqrt(tf.cast(h,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(h,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [ ]:
j=tf.constant(np.array([3,7,9,10]))
j

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([ 3,  7,  9, 10])>

In [ ]:
np.array(j),type(np.array(j))

(array([ 3,  7,  9, 10]), numpy.ndarray)

In [ ]:
j.numpy(),type(j.numpy())

(array([ 3,  7,  9, 10]), numpy.ndarray)

In [ ]:
j=tf.constant([3])
j.numpy()

array([3], dtype=int32)

In [ ]:
numpy_j=tf.constant(np.array([4,2,6,8]))
tensor_j=tf.constant([4,2,6,8])
numpy_j,tensor_j

(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([4, 2, 6, 8])>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 2, 6, 8], dtype=int32)>)

In [ ]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Mon Jun  1 15:02:18 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   52C    P0             27W /   70W |     109MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----